version: 2.1

defaults: &docker_img
  docker:
    - image: circleci/node:13.8.0
jobs:
  build:
    <<: *docker_img
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    <<: *docker_img
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    <<: *docker_img
    steps:
      - checkout
      - run: npm i
      - run: npm run audit


workflows:
  ci_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
        